# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd6bd75c4c277919d5a1708cb114d0f6a3522883dfed6ecffdf085d0af18d9fc668f1b76eb4165e5b3e046d7d4401fb42e97f12a2850279b4189892720eb955c

test:
  secret_key_base: 3ef9ca13a2989fc57db91cc2469cd826a8ee5ac8bc840d3c3162e38572eb4ca1ca8894c9a1a7fef42127a92019260971880c01423bd1e4942c2f0c16ce0e9233

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
